version: '3.8'

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-app
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - .env
    environment:
      - APP_ENV=local
      - CONTAINER_ROLE=app
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini:delegated
    networks:
      - hotel-network
    depends_on:
      - db
      - redis

  # Vite Development Server
  vite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotel-vite
    command: sh -c "npm install && npm run dev"
    working_dir: /var/www/html
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www/html:delegated
      - /var/www/html/node_modules
    networks:
      - hotel-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: hotel-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:delegated
    depends_on:
      - app
    networks:
      - hotel-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: hotel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:delegated
    ports:
      - "3306:3306"
    networks:
      - hotel-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: hotel-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - hotel-network

networks:
  hotel-network:
    driver: bridge

volumes:
  dbdata:
    driver: local 